---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-api-secrets
  namespace: demo
spec:
  encryptedData:
    JWT_SECRET_KEY: AgCB78yHgwH60o0EIfT6+OpVGntwnIcGIIJ+oj2igNxogYZbnHow5JsPgkpNMTyMvZxg7qEQlTxleyga9/LBgcPyC3yBa2cp8ygWMUxU2yJf9rTg1eOkkJJ7LnKnPjnqvt7OJI5ujYq1vRmvH7dFp48Lar4LbSJahRAolYj+LuMk/h53wGVJyfoX6du2uF40f6/UOU0xbk8E59LqOHGN352wf2i+j/CUAHezRxpuusOVD58XGQPTegFIK/S56iI9I1f3blpUfhGs1ZyYXL81T3tpvA53UOABV+CWFOPfwXzryODCsf+m1r6C45DlZ5V28rYriD8P1J1gZLaXDuakVyl0jLGUsneNUDPU4ESqTOPjq7wQNsnrGLGSXW8KOQg5NKmpGnHzYO5OZjNUFZQ/zxll32EPhgj/NbEvfN98vLPqZ/AB/RtiIQSz9iZYA26LNAl+DiV2utP5dCGwHcwI7gRtZmP2H4SWc3GbxI5gsrwPtDDiAYmBwz6qbINbLPwzEukzX5awc2oQmrgfazJqzEijd2w1qUNNlGmA/+GP0p74zzdx6h1TP35ai5sF6JWT/cq0IZ5RFHsrRD9pCXbKpgQRc6q6mVcnEkOd/1JqLMB4IM8uMgyN/8c5FbPjQ/GKNbsCYQ3al79DzsAQ2poktN7xP7xqkLKMCmS+QnHoePNVbOw/S88lElL/KlPDLqXontyLduU5JCFXoMM5RlevFmb+p6Q5zKNPjf7Qpx/zG9j8ABSW9aAFHZQtxlDPwZf8pu6AAgkCyCwRlFkFcZVhRp8x
  template:
    metadata:
      name: app-api-secrets
      namespace: demo
