---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-app-creds
  namespace: demo
spec:
  encryptedData:
    password: AgCzFZrviY1TaLZmLQckM4jhVpsYK8HSHDf3EtSqAPfCf7H5BuApV6Ic4XGyTqbmyifa/qBjTg+GJvGSRCnOpnOCYkxPwHkuuFUAE8dnrzqwO0omfRKrDlZUmEWS4dILac14jOXZ5iUXDW6csI5DNmDxUeW69a8d4uNUiUvkHKKUB9KQ+wZVHo+s1lB+C7ebXx2rV+6tDAfQ0Y81xTUgP5u5JYp5rtPHV+3kohb5MMUXIPy0TWY9aQtf/Z9mnv4QEsFIIhYiABUm4siB3plbe9fMcP0WWJghzkSRTqztI50dU0JlZUu98d9KpA0fmsag+DA5wkxwkkqh6/+THO/ZRXHF5XZsOHZFYtZXUZi+idadvEsLJyGLbIU2HkqY5WpzVkFgL6jWndNICZ9ab3MygggeaXKJi8uMZC7YSusGroVfoY1LRjIsgPgr8ZGuTrBIfdoyDr+5ipinBOxxeBPlQDPH2AzS6vx/cnfQepO2pWmOyYSGw5RDLzs+xFmI0hhGAZ9xjnONKPkIaedMNsS+Qds+OD8SnnpiFk2D4wwtbu4QUA2VhoSLml8+m5PJ7LSXcpgpfdN2lRFCtZDDdMTsO1/0aIxyNKfelA4gzyEfvWJHoJl5y7aLwqe3hGqSh0plgEww1TaVH54DCwEi7toT8nkAGAFyywyO3AW7z8QhKUPM3vkmW1fSTBWp/NtR4ZxSYpGEpFefg1jViR3z7m2V7a4dDkM8f65L74E=
    username: AgB3bk7HNyxjvs9rNEGMc2YM9DYkUywjZG8LNPgVx3JKO2RdgryZqLYgQASw+4TdSO4X1MTPSacvyuwsyIYQ/Iyi0QyJZfqbIhz7ugYCr3hktCrnyA6xXxlyJwJRjrTGB1M1fTNsIpO+8YAhoLkt1h9XMMm5W4VqFa1K/D1CumIdq3M14a3UbNR5IxwNtBoHFL5uwG9DZ4ogM9Syrl2kQvaBw5x18EMmXJoLtoqDTMiAd3ckmps2edagIs0HcpvcUAZajvsT3T0WtP4TiEUnPLfBsqmt6sdKJfEU8hAB5MR24c/4HRX9Pu6dEwwzy+tMSa/lK9z7HmuVXBxzyZ5Xvv5OBRHhSjVYyurdTXB04hgalyLrTxPH1H0NEjN5avQaHxIfoBbL7eCLDAkJH75zrE7qHuf0J8VHNpGSj0Lv0Kh2FXwWC+63VK2hNd7LHjmy1EhLGbBxZ41q72Hl4sjCwBTEQmd6SrNO2cP3DMS/NVv4K558t9JYHd2pg94jByCRbnPRNYjGX5tQuXkDkqcWIBxDmjjPdcDrvMz5BFXFQ0jfl7DC06mqnVAM5u3fjw1SRLHsu9csERFoX/E0SdBohQ2fqCldI7IlWOxYUzwdwAFEU5t9bd9oHbhrTtAmC4+DGzQlcuHzR+sqyjs/CGPb33aJJHzdLfCJ5wJV/POy6JLtjwIecOW8FH29cXb6oNuUDHst4LY=
  template:
    metadata:
      name: cnpg-app-creds
      namespace: demo
