---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: demo
spec:
  encryptedData:
    rootPassword: AgCXul2ZLmcwhapl6+vWJ/n5mkaxzla/5HU9uDg1HrcDpkIN3pW6kz3RQqAC6IUYMq3KyAVUJhcbifQ8CaC/454DdF8/VqH3q2POc56un/H1aGifyfyjZlgRVZfypwy1wxjqlKWR+pbY1a09zDloN5Ob5sGPV8u1l9xop7E5rYLsj47z53fSWsid5iQq5M9KEYnNb1l4E/J8hkGUdDuj/Xn1CD1kDYyxa+pOGH++CNf9F2zWG3MxOchaPypiJc8XgL2dRzVzdn2cDLj1Rz11eWSeCPIlXQzKEVai2wAAiplA/4E+26MP83zAO5yuIXAxD4UeeiiO6p/tVjYNzvgaW5Hl/3jbI096pvrpEfeJsx9StkTd2edwM+iYxN6gtBojZVzHdOqXDyvJxYjLszF0b1vFZx+9O6n8WXyPZTz0SkIFOtmAgP33VT8KRgeunapqovRlL7YSaa/kKaqlHD2ZZiB0ssyeTpmbqFrC8Frx1DmaloBPavkcqiqrfttq9w4L0gEdoUyViKR0MxKA2osm4U0gY8eJSZ6/MCdRul+VIDEG2jSVMBeEDTwhuwAYNed4XyDUKiik2289Bd5Ji/kuTzIgy867lgBGZl2sIi0SWtwONHAtcX3Vh/z3gJPDeRbJ10WuDqS1m9eWSGtD3HXmUk3hzSm9OYTyuKeWUkzY1nQsJyJF0M9/n76ZhWLRqK/hJCrsTHSZr83RFr16HT1s2LaCUYhU9Ee8sj8=
    rootUser: AgCDjL1gkvUMlo8pKTkTJjxgV4Vmv0lfFEozW6RpVkJwLuIxFZF6uvucLLyuQj/pYimb4p/JqWYvDsaMIUwVXMix8groiWu+7l8VE/Qiug3R7cj3SbNjdqGAvEDJgIZxucHaf5qCguMd2kEvmix5axafRxQXlVkidVamLQrei9eE+uy26w/Y6hh7foYUciigfvS1T0r19KPe95g/7Mk3CMDQSFTbuuWkgQvxYfc+vAaYx7N3EvYbvx/VXTvDmxc+T1yMFVWGO0mHJWACu5vaDQeej4nj5TzXbdEQ5yNXfRbO0u8r9CvWqrIv2/j+z7u6BF2DudTv7+o69gmVAcMV7kB+jehxzj4eH/5GiFrWSm9k0KflU1tcK3JNfJKRlXw09wTNd9rs4H0DnZm4Y0wLJ5oaxWH2+H9UhMj4OSvHy1BXvuUr7BnLQ8CrIAVWzVLDfR21uZqCCZwUvfrXXKclU7PB7IEx0/BqTgRjCEPkLo8AzYVY2Dc2t3bWlck48fpVJZw866CP3KNZ9JHFFh/kTlPfp4Fp7zYHwwQPY7zR4IRjItLD/UvcPrnTWu4d9rutdQoCICIquVl9j8jpAUumSbylAiJAPeupkwulE0jWj5Y/kkpq1wV5HJjR32v5c9ZNj+qvAhvDJzHF2IYADhhKEiG/qIBZLVZwVhfvxp9xwwbsohQ7l7UoqtzCLeEyhs3qAi20zzI7yzif4sFl
  template:
    metadata:
      name: minio-creds
      namespace: demo
