---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: demo
spec:
  encryptedData:
    redis-password: AgAdUGwvIptAvLE4hLQJnj5EpZXRRlc+cy5U9V0Bhfes1aqPqAGRDooxvPzY7NtFU60y76wWcnMnfX9HSAYPlcmS9m1IHgQYrpr9VvOOEfKYTTEdUMm7q1xfzZZC7yG1Likd4vLaRrgMYzCZNZf0fkLw5M0KSZFY/PypBU84O3eSXaM3VobUY+clz/k5I9/gBT7uQjFEA3rC4jMhvt4jMVeYb4dsvbHVMj3XIO3RbomkAo/WQmJwqmyZ+FaSuThgCRwJPZGO9TG6RI86YMHoqQRnGkEgkA0wmB1c28D723KIf81UcaDc06XYllT2KlXv6O1h3Xhk6SRYxaCjHCMtj99E/4oKDnsQ7aKbAV2XXFkgUn0IYG+bXBczElw6N3w1XJvwrh1rVH8nl9ztygccoxFSWHIMUcM4+EdNG3uE3OCX3yTMZM8307nIdV1wSWEVKFmAKzl5RuCNnxg8Ri5qz93dwXAZFVtwH3Ai+ir+4G5hN1fv2yIuWjqH5fE5W+ZUy6oVxl8+QAyn4Aqtrsr2i5UsBOQL87CvcEENKi8Kdlr8C8AFwKLjZmKtQ1y3MTqtHk/C53j9w5b0apTKr2iV49/+j2k59af95rLzG5rh9wd3pPkbcNq9GedYNXNY4fj1sHiFGTXem9fVv2aH/M1duCEv3SMLrk4cXH9yCqvkcvVAxhWV/d61HULBOfoMZA6OOqZfTSiVGO8YzBHKPqTKL7Ughpl62JT9htw=
  template:
    metadata:
      name: redis-password
      namespace: demo
