apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "video-demo.fullname" . }}-{{ .Values.component }}
  labels:
    {{- include "video-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "video-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "video-demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.component }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.commandOverride }}
          command: {{ .Values.commandOverride.command | toJson }}
          args: {{ .Values.commandOverride.args | toJson }}
          {{- end }}
          {{- if .Values.service.enabled }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- end }}
          {{- if .Values.configMap.enabled | or .Values.sealedSecret.enabled }}
          envFrom:
            {{- if .Values.configMap.enabled }}
            - configMapRef:
                name: {{ include "video-demo.fullname" . }}-config
            {{- end }}
            {{- if .Values.sealedSecret.enabled }}
            - secretRef:
                name: {{ include "video-demo.fullname" . }}-secrets
            {{- end }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.health }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health.liveness }}
              port: {{ .Values.health.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.health.readiness }}
              port: {{ .Values.health.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
