{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "video-demo.fullname" . }}-secrets
  labels:
    {{- include "video-demo.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealedSecret.encryptedData }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ include "video-demo.fullname" . }}-secrets
      labels:
        {{- include "video-demo.labels" . | nindent 8 }}
{{- end }}
