minio:
  mode: standalone
  replicas: 1
  persistence:
    size: 1Gi
  existingSecret: minio-creds
  buckets:
    - name: video-demo
      policy: none
      purge: false
  resources:
    requests:
      memory: 256Mi
  commonAnnotations:
    argocd.argoproj.io/sync-wave: "3"
