apiVersion: v2
name: demo-redis
description: Wrapper chart for bitnami/redis
type: application
version: 0.1.0
appVersion: "7.0"

dependencies:
  - name: redis
    version: "~23.x"
    repository: https://charts.bitnami.com/bitnami
