redis:
  architecture: standalone
  auth:
    enabled: true
    existingSecret: redis-password
    existingSecretPasswordKey: redis-password
  master:
    persistence:
      size: 512Mi
  commonAnnotations:
    argocd.argoproj.io/sync-wave: "2"
